apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: gitlab
spec:
  containers:
    - name: web
      image: registry.gitlab.com/gitlab-org/build/cng/kubectl:1.16.15
      command:
      - /bin/bash
      - -c 
      - sleep 10000
      securityContext:
        runAsUser: 0
  serviceAccount: gitlab-shared-secrets
  serviceAccountName: gitlab-shared-secrets